params:
  env: production

  homeInfoParams:
    Title: Dan Oak - Software Engineer
    Content: Welcome to my Blog

  socialIcons: # optional
    - name: twitter
      url: "https://twitter.com/CoderDan"
    - name: github
      url: "https://github.com/DanDecrypted"